version: '3'

services:

  agent0:
    build:
      context: .
      target: threepc
    image: opencbdc-tx-threepc
    tty: true
    restart: always
    command: ./scripts/wait-for-it.sh -s ticket0:7777 -t 60 -- ./scripts/wait-for-it.sh -s shard0:5556 -t 60 -- ./build/src/3pc/agent/agentd 0 0 test.cfg agent.log
    ports:
      - 8888:8888
    networks:
      - 3pc-network
    healthcheck:
      test: ["CMD-SHELL", "netstat -ltn | grep -c 6666"]
      interval: 30s
      timeout: 10s
      retries: 5

  agent1:
    build:
      context: .
      target: threepc
    image: opencbdc-tx-threepc
    tty: true
    restart: always
    command: ./scripts/wait-for-it.sh -s ticket0:7777 -t 60 -- ./scripts/wait-for-it.sh -s shard0:5556 -t 60 -- ./build/src/3pc/agent/agentd 1 0 test.cfg agent.log
    ports:
      - 8890:8890
    networks:
      - 3pc-network
    healthcheck:
      test: ["CMD-SHELL", "netstat -ltn | grep -c 6666"]
      interval: 30s
      timeout: 10s
      retries: 5

  ticket0:
    build:
      context: .
      target: threepc
    image: opencbdc-tx-threepc
    tty: true
    command: ./scripts/wait-for-it.sh -s shard0:5556 -t 60 -- ./build/src/3pc/ticket_machine/ticket_machined 0 0 test.cfg ticket.log
    networks:
      - 3pc-network
    healthcheck:
      test: ["CMD-SHELL", "netstat -ltn | grep -c 7777"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  shard0:
    build:
      context: .
      target: threepc
    image: opencbdc-tx-threepc
    tty: true
    command: ./build/src/3pc/runtime_locking_shard/runtime_locking_shardd 0 0 test.cfg shard.log
    networks:
      - 3pc-network
    healthcheck:
      test: ["CMD-SHELL", "netstat -ltn | grep -c 5556"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

networks:
  3pc-network:
    name: 3pc-network
